/**
 * @fileOverview SEO Change Resolution Model.
 * Represents the "After" state generated by AI for a specific optimization task.
 */

export enum SeoChangeType {
  META_UPDATE = 'META_UPDATE',
  SCHEMA_INSERT = 'SCHEMA_INSERT',
  ENTITY_LINK_INSERT = 'ENTITY_LINK_INSERT', // New type for Knowledge Graph links
}

export interface SeoChange {
  changeType: SeoChangeType;
  pageUrl: string;
  before?: any;
  after: any;
  confidence: number;
  notes?: string;
}
