import { WordPressPost } from './wordpress.types';
import { SitePage } from '@/modules/sites/entities/site-integration.entity';

/**
 * @fileOverview Data mapper for WordPress objects.
 * Converts raw WordPress responses into internal domain models.
 */

export class WordPressMapper {
  /**
   * Maps a WordPress Post/Page to our internal SitePage entity.
   */
  static toSitePage(orgId: string, siteId: string, wpPost: WordPressPost): SitePage {
    return {
      id: `${siteId}_${wpPost.id}`,
      organizationId: orgId,
      siteId: siteId,
      wpPostId: wpPost.id,
      url: wpPost.link,
      title: wpPost.title.rendered,
      contentHash: '', // To be generated by service
      lastSyncedAt: new Date().toISOString(),
    };
  }

  /**
   * Prepares SEO metadata based on the plugin configuration.
   */
  static mapSeoMetadata(
    plugin: 'yoast' | 'rankmath' | 'none',
    title?: string,
    description?: string,
    jsonLd?: string
  ): Record<string, any> {
    const meta: Record<string, any> = {};

    if (plugin === 'rankmath') {
      if (title) meta.rank_math_title = title;
      if (description) meta.rank_math_description = description;
    } else if (plugin === 'yoast') {
      if (title) meta._yoast_wpseo_title = title;
      if (description) meta._yoast_wpseo_metadesc = description;
    }

    if (jsonLd) {
      meta._agentpro_json_ld = jsonLd;
    }

    return meta;
  }
}
