apiVersion: v1
kind: Service
metadata:
  name: agentpro-svc
spec:
  selector:
    app: agentpro
    component: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
