/**
 * @fileOverview SEO Change Category Types.
 */

export enum SeoChangeType {
  META_TITLE = 'META_TITLE',
  META_DESCRIPTION = 'META_DESCRIPTION',
  SCHEMA_INSERTION = 'SCHEMA_INSERTION',
  SCHEMA_FIX = 'SCHEMA_FIX',
  ALT_TEXT = 'ALT_TEXT',
  DUPLICATE_H1 = 'DUPLICATE_H1',
  INTERNAL_LINK = 'INTERNAL_LINK',
  THIN_CONTENT = 'THIN_CONTENT',
}
